- primer3/thermoanalysis.pyx
- setup.py
Setuptools [supports](https://github.com/pypa/setuptools/blob/master/CHANGES.rst#180) building .pyx files as extensions. This PR takes advantage of that mechanism and avoids importing cython in setup.py. This allows primer3-py to be installed into an environment where cython was not previously installed.
This is helpful for me because I have a package A, which depends on a package B, which depends on primer3-py. When I am testing package A, I want tox to install package B from git; there's no opportunity to install cython into the tox environment before it tries to install package B (or its dependency primer3-py).
Oddly, this requires avoiding build_ext. Setuptools checks to see whether it can import cython when the build_ext command is imported. Setuptools intentionally delays the …
> Use setup_requires cython pattern

- primer3/bindings.py
- primer3/src/libprimer3/libprimer3.c
- primer3/src/libprimer3/thal.c
- primer3/src/libprimer3/thal.h
- primer3/src/libprimer3/thal_main.c
- primer3/thermoanalysis.pxd
- primer3/thermoanalysis.pyx
- primer3/wrappers.py
- tests/test_thermoanalysis.py
This adds support for ASCII structure string generation in the bindings for homodimer, heterodimer, and hairpin calculations. For example:
```
>>> import primer3
>>> res = primer3.bindings.calcHeterodimer('CCCCTCCCC', 'GGGGTGGGG', output_structure=True)
>>> print(res.ascii_structure) 
SEQ	    T    
SEQ	CCCC CCCC
STR	GGGG GGGG
STR	    T    
```
If the `output_structure` kwarg is set to `True` for `calcHeterodimer`, `calcHomodimer`, or `calcHairpin`, the ASCII structure will be generated and stored in the `ascii_structure` property of the `ThermoResult` object. 
Addresses request in #28.
> Support generation of ASCII structure strings

- .pre-commit-config.yaml
- docs/conf.py
- primer3/__init__.py
- primer3/bindings.py
- primer3/src/primerdesign_helpers.c
- primer3/src/primerdesign_py.c
- primer3/thermoanalysis.pxd
- primer3/thermoanalysis.pyx
- primer3/wrappers.py
- setup.py
- tests/_simulatedbindings.py
- tests/checkdatasets.py
- tests/test_primerdesign.py
- tests/test_thermoanalysis.py
type hinting of all python and cython code.
cython code style update
cython `property` decorator update
NOTE: `cpdef` code has difficulties with type hinting with `.pxd` file
[`mypy`](https://mypy-lang.org) added to `pre-commit` hooks
`cythonize` added to `setup.py` to get `language_level=3` compiler directive.  
Python 3.8 to 3.11 only now based on easily available CPython packages in conda channels used during development.
`wrappers.py` and `primerdesign_helpers.c` and updated to remove Python 2 related code
update to 1.0.0-alpha.3
> type hinting, `cython` style update, `pre-commit` `mypy`

- primer3/argdefaults.py
- primer3/bindings.py
- primer3/src/primerdesign_py.c
- primer3/thermoanalysis.pxd
- primer3/thermoanalysis.pyx
- primer3/wrappers.py
Goal is to match defaults of Primer3web at https://primer3.ut.ee
added `argdefaults.Primer3PyArguments` to unify default value locations.
Removed `primerdesign_py.c` Python2 legacy code
return `ThermoAnalysis.tm_method and `ThermoAnalysis.salt_correction_method` as strings when get as a
property to abstract integer values from developer using the class
removed `ThermoAnalysis.thal_type` as unused in practice and each class method sets the correct value for this argument
> Unify global defaults in new `argdefaults.py` module.

- .github/workflows/primer3-py-ci-github-action.yml
- primer3/__init__.py
- primer3/bindings.py
- primer3/thermoanalysis.pyx
- primer3/wrappers.py
Includes incidental fix in `thermoanalysis.pyx`
- `c_ascii_structure[0] = '\0';` -> `c_ascii_structure[0] = b'\0';`
> Remove `PRIMER3HOME` in favor of package-relative paths

- primer3/argdefaults.py
remove `kw_only` kwarg for `dataclass` as it is Python 3.10 only
> `kw_only` dataclass fix primer3 py arguments

- primer3/src/libprimer3/amplicontm_main.c
- primer3/src/libprimer3/libprimer3.c
- primer3/src/libprimer3/oligotm.c
- primer3/src/libprimer3/oligotm_main.c
- primer3/src/libprimer3/p3_seq_lib.c
- primer3/src/libprimer3/primer3_boulder_main.c
- primer3/src/libprimer3/read_boulder.c
- primer3/src/libprimer3/thal.c
- primer3/src/libprimer3/thal.h
- primer3/src/libprimer3/thal_main.c
- tests/test_thermoanalysis.py
1. `primer3-py` specific comments added/updated for C code.  
2. Updated `strcmp` code for bugfixes due to insufficient parse character count in `amplicontm_main.c`, `oligotm_main.c`, and `primer3_boulder_main.c` related to several parameters in the code.
NOTE: possibly `strlen` should be called to confirm argument lengths prior to comparison.
3. added `test_max_length_heterodimer` and docstrings to `test_thermoanalysis`. Can confirms stack allocation of ~ 41000 works for `duplex_buffer` in `drawDimer` on MacOS 13.2
4.  Fixed order does not matter arguments in the `binding_12_res` /
`binding_21_res` in `test_calc_heterodimer`.  
5. initialize of `s` pointer to `NULL` in `read_bould_record` to address compiler warning
> code clarity and comments update.  `*_main.c` argument parsing fixes 

- primer3/src/libprimer3/libprimer3.c
- primer3/src/libprimer3/thal.c
- primer3/thermoanalysis.pyx
- setup.py
A small assortment of changes to fix build on windows:
1. `OS_WIN` not defined in `libprimer3.c` or `#include`'d headers (added)
2. MSVC doesn't support variable length C99 arrays (add cond'l malloc for win)
3. Need to set `TESTOPTS=--windows` in `make` invocation on Windows
4. Move `thermoanalysis` conditionals from runtime to preprocessor (no masker support on windows)
> Fix windows build

- .github/workflows/build-wheels-pypi.yml
- docs/quickstart.md
`conda` channel builds work is not complete.  
Remove an extra 'to' word from `build-wheels-pypi.yml`
> Removed `conda install` instructions in `quickstart.md` and fix typo

- .github/workflows/build-wheels-pypi.yml
- docs/quickstart.md
Wheel build support for python 3.8 to move towards following the CPython
EOL model. https://devguide.python.org/versions/
Added NOTE about it in `quickstart.md`
addresses #88 which will close once `1.1.0-staging` merges into `master`
> python 3.8 wheel support

- .github/workflows/build-wheels-pypi.yml
- CHANGES
- docs/quickstart.md
- primer3/__init__.py
- primer3/src/libprimer3/libprimer3.c
- Added specificity to error non-N IUPAC error for issue #59
- Wheel build support for python 3.8 to move towards following the CPython EOL model for issue #88. See https://devguide.python.org/versions/
> 1.1.0 release 

- .gitignore
- MANIFEST.in
- docs/api/index.md
- docs/api/p3helpers.md
- docs/quickstart.md
- primer3/bindings.py
- primer3/p3helpers.h
- primer3/p3helpers.pyx
- primer3/thermoanalysis.pyx
- setup.py
- tests/test_p3helpers.py
Sequence sanitization of IUPAC non-{A,C,G,T,a,c,g,t} bases become {N, n} and also reverse complement added.  Separate methods exist for byte strings and unicode strings with error handling.
The intent is `p3helpers.pyx` will be a separate module for helper functions for primer design that exist outside of the separate`libnano/libnano` package prior to its update and release.
`docs/` updated to support `p3helpers.pyx` and remove duplicates in the documentation.
This PR will help address issue #57
> `p3helpers.pyx` houses new sequence and design helper functions

- CHANGES
- primer3/__init__.py
- primer3/bindings.py
- primer3/src/libprimer3/thal.h
- primer3/src/libprimer3/thalflex.c
- primer3/src/libprimer3/thalflex.h
- primer3/src/libprimer3/thalflexsignatures.h
- primer3/thermoanalysis.pxd
- primer3/thermoanalysis.pyx
- setup.py
- tests/test_threadsafe.py
New `thal.c` code lives in `thalflex.c` and `thalflex.h` and `thalflexsignatures.h`.
Commented out code in `thalflex.c` used MacOS `<malloc/malloc.h>` `malloc_size()` function to investigate allocations of `triloopEnthalpies/triloopEntropies` and `tetraloopEnthalpies/tetraloopEntropies`
`test_threadsafe.py` add and `nogil` instituted for calls to `thal()` and `seqtm()` added `run_design` and `calc_heterodimer` threadsafe tests
Presently  `thermoanalysis.pyx/pxd` have been update to use `thalflex.c ` and `nogil` cython instruction resulting in a 20X speed improvement on MacOS development machine (2X from `thalflex.c` and 10X from `nogil`)
`ThermoAnalysis` class no longer needs to be a `Singleton` so this was removed as a parent class
version bump to 1.2.0a1
`CHANGES` update for 1.2.0 …
> thread-safe `thal.c` code and `nogil` updates for `ThermoAnalysis`

- CHANGES
- primer3/__init__.py
- primer3/thermoanalysis.pxd
- primer3/thermoanalysis.pyx
- tests/test_primerdesign.py
`pdh_create_seq_lib` updated to correct missing `seq_lib` datastructure allocation and variable name typos.
Increase test coverage to include `misprime_lib` and `mishyb_lib` arguments
version bump to 1.2.1
> bug fixes for issue 101. `pdh_create_seq_lib` to bug fixes

- CHANGES
- primer3/__init__.py
- primer3/thermoanalysis.pyx
See #104 -- constitutes patch release:
```markdown
- Bug fixes for output formatting related to penalty, "problem", and mispriming fields
```
> Output-related bug fixes

- CHANGES
- MANIFEST.in
- primer3/__init__.py
- primer3/thermoanalysis.pxd
- primer3/thermoanalysis.pxi
- primer3/thermoanalysis.pyx
- setup.py
To enable cleaner third party use of `primer3-py` in cython applications, it's useful to remove header file imports.
This was accomplished with "shadow" structs for: 
- `thal.h/thal_args` --> `thermoanalysis.pxd/p3_thal_args_t`
- `thal.h/thal_results` --> `thermoanalysis.pxd/p3_thal_results_t`
And by converting pointer attributes to `void* 
- `p3_global_settings* global_settings_data` --> `void* global_settings_data`
- `seq_args_t* sequence_args_data` --> `void* sequence_args_data`
This change, and using the appropriate type casts in  `thermoanalysis.pyx` enabled a move of all extern header imports to a new file  `thermoanalysis.pxi`
It is now cleaner to make a `from primer3.thermoanalysis cimport _ThermoAnalysis` call in 3rd party software with no need for any header files from the …
> migrated primer3 header file Cython extern imports to `thermoanalysis.pxi`

- CHANGES
- docs/cython_help.md
- primer3/__init__.py
- primer3/thermoanalysis.pyx
- tests/test_primerdesign.py
see issue #50 
`PRIMER_{PAIR, LEFT, RIGHT, INTERNAL}` output dictionary keys. 
Retaining original keys as well for compatibility
version bump to 2.0.0
Updated `CHANGES`
Updated `cython_help.md` for a note about the `c_ascii_structure` argument from a previous PR #100
> Nested structure for primer results 

- CHANGES
- primer3/src/libprimer3/libprimer3.c
- primer3/src/libprimer3/libprimer3flex.c
- primer3/src/libprimer3/thal.c
- primer3/thermoanalysis.pyx
- tests/test_primerdesign.py
For issue #111 to address missing `thal_result.sec_struct` and `dpal_results.sec_struct` initialization to `NULL` in `recalc_primer_sec_struct` in `libprimer3.c` and `libprimer3flex.c`
This resulted in `PRIMER_SECONDARY_STRUCTURE_ALIGNMENT` being set to 1 causing a segmentation fault.
> Hotfix `recalc_primer_sec_struct` missing `thal_result.sec_struct` initialization to `NULL`

- primer3/thermoanalysis.pyx
- tests/test_thermoanalysis.py
Addresses #122 -- fixes incorrect ``Thermoanalysis`` property reference in ``Thermoanalysis.todict``, an incidentally discovered bug w/ the `salt_correction_method` property getter, and adds `todict` coverage
> Fix ``todict`` method of ``Thermoanalysis`` and add unit test coverage

- .github/workflows/build-wheels-pypi.yml
Fixes build issue seen in this action pipeline: https://github.com/libnano/primer3-py/actions/runs/7845582538
Post-fix pipeline: https://github.com/libnano/primer3-py/actions/runs/7845449730
> Update `cibuildwheel` to latest release for python 3.12 build support

- CHANGES
- primer3/__init__.py
- primer3/src/libprimer3/libprimer3flex.c
- primer3/thermoanalysis.pyx
- tests/test_primerdesign.py
Fix `_ThermoAnalysis._set_globals_and_seq_args` for improper checks on `misprime_lib` and  `mishyb_lib` leading to incorrect initialization of `mp_lib` and `mh_lib` and extensive run delays.  See #133 
```python
import time
from primer3 import __version__
from primer3.bindings import design_primers
ref_fasta = 'NC_004547.2.fa'
seq = '''\
GATTGATTGAAGTCCAGGCACCGATTCTCAGCCGTATCGGCGATGGCACACAGGATAACTTGTCTGGTAC
AGAAAAAGCGGTGCAGGTTAAGGTAAAAGCCTTACCGGATGCCACATTTGAAGTGGTGCACTCACTGGCA
AAATGGAAACGCAAAACGCTGGGCGCGTATGATTTTAGCTTCGGTGAAGGCATTTATACTCACATGAAGG
CGCTGCGTCCGGACGAAGATCGCCTGAGCCCGATCCACTCGGTTTATGTCGATCAGTGGGATTGGGAGCG
CGTGATGGAGGATGGCGAGCGCAATGCTGAATATCTGAAATCGACGGTCACGCGTATTTATCAAGGCATT
AAAGCGACTGAGGCTGCGGTACATCAGGCGTTTGGCATTCAGCCTTTCCTGCCAGAGCAGATTCATTTTG …
```
> Fix `_ThermoAnalysis._set_globals_and_seq_args` for improper checks on `misprime_lib` and  `mishyb_lib`

- CHANGES
Closes #133, although you may wish to do the line breaks differently?
> Clarify how to replace setGlobals as of v1.0.0

- CHANGES
- primer3/__init__.py
- primer3/src/libprimer3/ABOUT.txt
- primer3/src/libprimer3/libprimer3flex.c
- primer3/thermoanalysis.pyx
- tests/test_primerdesign.py
- Clarify how to replace setGlobals as of v1.0.0 (#134)
- Fix _ThermoAnalysis._set_globals_and_seq_args for improper checks on misprime_lib and mishyb_lib (#135)
> 2.0.3 release

- .github/workflows/primer3-py-ci-github-action.yml
- .pre-commit-config.yaml
- primer3/src/libprimer3/thalflex.c
- tests/test_threadsafe.py
`primer3-py` does not rely on any of the original `stderr` print behavior of the `primer3` library -- any desirable text output is written to internal buffers rather than `stdout` or `stderr`. In cases where the text output was not needed for `primer3-py` functionality, it was disabled behind preprocessor directives (i.e., it could re-enabled for debug purposes with a respective flag). This PR fixes one outstanding instance of `stderr` printing that did not have this debug flag guard installed.
Addresses issue #146. Note that I also had to make some incidental changes to the `pre-commit` configuration (due to out of date dependencies, sunsetting of the inclusion of `setuptools` in `stdlib`, etc. That means this PR now supercedes  #143
> Add missing DEBUG flag guard around stderr message in thalflex

- .github/workflows/build-wheels-pypi.yml
- .github/workflows/update-docs.yml
- docs/miscellany.md
- docs/quickstart.md
- primer3/__init__.py
- setup.py
Adds support for Python 3.13 (as well as some incidental fixes for various GH actions deprecations).
Successful GH action pipeline run (wheel/sdist build): https://github.com/benpruitt/primer3-py/actions/runs/13359997780
> Python 3.13 Support

- .github/workflows/build-wheels-pypi.yml
- .github/workflows/primer3-py-ci-github-action.yml
- .github/workflows/update-docs.yml
- .pre-commit-config.yaml
- CHANGES
- docs/miscellany.md
- docs/quickstart.md
- primer3/__init__.py
- primer3/argdefaults.py
- primer3/src/libprimer3/thalflex.c
- setup.py
- tests/test_threadsafe.py
- Python 3.13 support (#148)
- Add missing DEBUG flag guard around stderr message in thalflex (#147, closes #146)
- Updated default formamide concentration to match latest primer3web value + oligotm default (closes #140)
> 2.1.0 release

- .github/workflows/primer3-py-ci-github-action.yml
- .github/workflows/update-docs.yml
`setuptools` was removed from the standard Python distribution in a 3.12.x point release, which broke this workflow. It has now been added back in as an explicit installation step (this also implicitly includes the `distutils` variant that ships w/ `setuptools`. 
I also modified the GH action `yaml` to include affordances for triggering the workflow manually and on any branch that contains `docs`. In the event that the workflow is triggered based solely on the branch name, the results will be pushed to the `gh-pages-test` branch (rather than `gh-pages`). Triggers based on `vN.N.N` tags or manual triggers push to `gh-pages`.
I don't think this needs to be wrapped up in a release as it doesn't touch distribution code; this PR directly targets `master`.
> Fix docs-building GH action

- primer3/thermoanalysis.pyx
- pyproject.toml
- tests/save_thermo_values.py
- tests/test_primerdesign.py
- tests/test_sequences.py
- tests/test_thermoanalysis.py
- tests/test_threadsafe.py
- tests/thermo_standard_values.json
Minor modifications to tests to ensure that they are deterministic (we've had issues with flakey tests due to our liberal use of `random` in the past). I didn't want to refactor too extensively so the big "fix" here is to just use seeds (in a thread-aware manner).
> Make tests deterministic

- .github/workflows/release.yml
- CHANGES
- primer3/__init__.py
- tests/thermo_standard_values.json
- Test improvements (determinism + increased coverage) 
- PR #158 
- Sanitize `calc_tm` input 
- PR #156 
- Closes issue #115
- Modernize build system & release process 
- PR #155 
- PR #157 
- Closes issue #154
Note that this release bumps `Cython` support to the latest release (`3.1.0`) and pins the major version (the `Cython` dep was previously unpinned, which led to #154). 
**Pre-merge checklist:**
**Dry run workflow instances:**
- [Release](https://github.com/libnano/primer3-py/actions/runs/15125374720)
- [Documentation](https://github.com/libnano/primer3-py/actions/runs/15124809403)
> 2.2.0 release
